### PR TITLE
fix staticcheck warnings

### LINKED ISSUE #190: Resolve staticcheck warnings
**how to reproduce:**

run `golangci-lint run --enable goimports --enable gofmt --timeout 10m` in the terminal

**Screenshot:**
Screenshot 2024-02-03 at 7 04 23 PM

### PR DESCRIPTION
**Pull request by kartikaysaxena**
Fixes #190

### CODE REVIEW

File: pkg/utils/experiment.go [hunk 1]
```diff
@@ -133,23 +133,14 @@ func ParseExperimentManifest(file string, chaosWorkFlowRequest *model.SaveChaosE
...
-// Helper function to check the presence of a string in a slice
-func sliceContains(s []string, e string) bool {
-	for _, a := range s {
-		if a == e {
-			return true
-		}
-	}
-	return false
-}
-
```
Comment (kartikaysaxena) [inline pkg/utils/experiment.go:145]: Removed it because the lint was complaining about unused helper function

File: pkg/utils/experiment.go [hunk 2]
```diff
@@ -133,23 +133,14 @@ func ParseExperimentManifest(file string, chaosWorkFlowRequest *model.SaveChaosE
...
 // Helper function to generate a random 8 char string - used for workflow name postfix
 func generateRandomString() string {
-	rand.Seed(time.Now().UnixNano())
+	source := rand.NewSource(time.Now().UnixNano())
+	randomGenerator := rand.New(source)
```
Comment (kartikaysaxena) [inline pkg/utils/experiment.go:139]: Changed because rand.Seed is depreciated as of now.

File: pkg/apis/infrastructure/infra.go [hunk 3]
```diff
@@ -45,7 +45,7 @@ func GetInfraList(c types.Credentials, pid string, request models.ListInfraReque
 		return InfraData{}, err
 	}
 
-	bodyBytes, err := ioutil.ReadAll(resp.Body)
+	bodyBytes, err := io.ReadAll(resp.Body)
```
Comment (kartikaysaxena) [inline pkg/apis/infrastructure/infra.go:48]: ioutil is deprecated in favour of io and os

**Comment by kartikaysaxena** [comment]
Screenshot 2024-02-05 at 3 14 42 AM
Now all warnings seems to be resolved.

**Review by neelanjan00 — APPROVED** [review]

File: pkg/apis/environment/environment.go [hunk 4]
```diff
@@ -18,13 +19,13 @@ func CreateEnvironment(pid string, request models.CreateEnvironmentRequest, cred
 	gqlReq.Variables.ProjectId = pid
 	gqlReq.Variables.Request = request
 
-	query, err := json.Marshal(gqlReq)
+	query, _ := json.Marshal(gqlReq)
```
Comment (Nageshbansal) [inline pkg/apis/environment/environment.go:22]: instead of replacing it with '_' , it will be better to have a not nil err check here.

File: pkg/apis/infrastructure/infra.go [hunk 5]
```diff
@@ -96,13 +96,13 @@ func ConnectInfra(infra types.Infra, cred types.Credentials) (InfraConnectionDat
 		gqlReq.Variables.RegisterInfraRequest.Tolerations = toleration
 	}
 
-	query, err := json.Marshal(gqlReq)
+	query, _ := json.Marshal(gqlReq)
```
Comment (Nageshbansal) [inline pkg/apis/infrastructure/infra.go:99]: add a not nil err check here

**Review by Jonsy13 — APPROVED** [review]

**Review by SarthakJain26 — APPROVED** [review]

**Comment by SarthakJain26** [comment]
@deep-poharkar @Nageshbansal please review this PR

**Comment by Nageshbansal** [comment]
Lgtm 🚀

**Comment by deep-poharkar** [comment]
looks good

**Comment by SarthakJain26** [comment]
@kartikaysaxena can you please try to resolve the merge conflicts, we can take this PR in litmusctl 1.3.0 release

**Comment by kartikaysaxena** [comment]
Hey @SarthakJain26, both my commits are signed off, and DCO is passing, but it is still showing that merging is blocked. Can you help with that?

**Comment by SarthakJain26** [comment]
It's because the build pipeline is failing, here are the logs: 
Screenshot 2024-02-15 at 3 12 11 PM

**Comment by SarthakJain26** [comment]
@kartikaysaxena looks like there's one merge conflict, can you try resolving that as well please

File: pkg/apis/infrastructure/infra.go [hunk 6]
```diff
@@ -189,43 +193,3 @@ func DisconnectInfra(projectID string, infraID string, cred types.Credentials) (
 		return DisconnectInfraData{}, err
 	}
 }
-
-// GetServerVersion fetches the GQL server version
-func GetServerVersion(endpoint string) (ServerVersionResponse, error) {
```
Comment (SarthakJain26) [inline pkg/apis/infrastructure/infra.go:194]: Please add back this function, looks like it was deleted while resolving the conflicts

**Review by SarthakJain26 — CHANGES_REQUESTED** [review]

**Review by SarthakJain26 — APPROVED** [review]

**Comment by SarthakJain26** [comment]
Thanks @kartikaysaxena for fixing this 🚀
